//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evdebitti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SEPET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_SEPET()
        {
            this.C_URUNLER = new HashSet<C_URUNLER>();
        }
    
        public int SEPET_ID { get; set; }
        public Nullable<int> S_URUNID { get; set; }
        public string S_URUNADI { get; set; }
        public Nullable<decimal> S_URUNFIYAT { get; set; }
        public string S_URUNRESIM { get; set; }
        public Nullable<int> S_URUNADET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_URUNLER> C_URUNLER { get; set; }
    }
}
