//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evdebitti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_URUN_KATEGORILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_URUN_KATEGORILER()
        {
            this.C_URUNLER = new HashSet<C_URUNLER>();
        }
    
        public int URUN_KATEGORI_ID { get; set; }
        public string URUN_KATEGORI_ADI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_URUNLER> C_URUNLER { get; set; }
    }
}
